id = "baizhu/catwalk"
name = "Catwalk"
version = "1.0.0"
plugin_api = 14
author = "<yourusername>"
license = "MIT"
dependencies = []
tags = ["bar", "fun"]
icon = "cat"
description = "A CPU-reactive animated cat for the Noctalia v5 bar."

[[setting]]
key = "minimum_threshold"
type = "double"
label_key = "settings.minimum_threshold.label"
default = 15.0
min = 0.0
max = 100.0
step = 1.0

[[setting]]
key = "external_monitor"
type = "string"
label_key = "settings.external_monitor.label"
default = "resources || missioncenter || jdsystemmonitor || corestats || system-monitoring-center || gnome-system-monitor || plasma-systemmonitor || mate-system-monitor || ukui-system-monitor || deepin-system-monitor || pantheon-system-monitor"
advanced = true

[[widget]]
id = "bar"
entry = "bar.luau"

  [widget.actions]
  left = "panel-toggle baizhu/catwalk:panel"
  right = "panel-toggle baizhu/catwalk:panel"
  middle = "none"

[[panel]]
id = "panel"
entry = "panel.luau"
width = 300
height = 300
placement = "attached"
position = "top_right"
